baseURL = 'https://tegakituesday.com/'
languageCode = 'en-us'
title = 'Tegaki Tuesday'
theme = 'tegakituesday.com'
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
	AuthorName = "Elnu"
	FontAwesomeKit = "c3c3b565dc"

[permalinks]
	pages = "/:title"
	challenges = "/:title"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true