baseURL = 'https://tegakituesday.com/'
languageCode = 'en-us'
title = 'Tegaki Tuesday'
theme = 'tegakituesday.com'
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
	AuthorName = "Elnu"
	FontAwesomeKit = "c3c3b565dc"
	MatomoURL = "matomo.elnu.com"
	MatomoSiteId = "4"

[permalinks]
	challenges = "/:filename"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
